/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminManager: typeof import('./../components/datahome/AdminManager.vue')['default']
    EchartsContainer: typeof import('./../components/datahome/EchartsContainer.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FlowStat: typeof import('./../components/datahome/FlowStat.vue')['default']
    LayoutContent: typeof import('./../components/layout/LayoutContent.vue')['default']
    LayoutHead: typeof import('./../components/layout/LayoutHead.vue')['default']
    LayoutMenu: typeof import('./../components/layout/LayoutMenu.vue')['default']
    Map: typeof import('./../components/datahome/Map.vue')['default']
    OrderTrendStatistics: typeof import('./../components/datahome/OrderTrendStatistics.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./../components/layout/test.vue')['default']
    TodayCurrentData: typeof import('./../components/datahome/TodayCurrentData.vue')['default']
    TopPurchase: typeof import('./../components/datahome/TopPurchase.vue')['default']
    TopWebsite: typeof import('./../components/datahome/TopWebsite.vue')['default']
    TypeDistribution: typeof import('./../components/datahome/TypeDistribution.vue')['default']
    UserTrendStatistics: typeof import('./../components/datahome/UserTrendStatistics.vue')['default']
  }
}
