/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AdminManager: typeof import('./../components/index/AdminManager.vue')['default']
    EchartsContainer: typeof import('./../components/index/EchartsContainer.vue')['default']
    FlowStat: typeof import('./../components/index/FlowStat.vue')['default']
    Map: typeof import('./../components/index/Map.vue')['default']
    OrderTrendStatistics: typeof import('./../components/index/OrderTrendStatistics.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./../components/common/test.vue')['default']
    TodayCurrentData: typeof import('./../components/index/TodayCurrentData.vue')['default']
    TopPurchase: typeof import('./../components/index/TopPurchase.vue')['default']
    TopWebsite: typeof import('./../components/index/TopWebsite.vue')['default']
    TypeDistribution: typeof import('./../components/index/TypeDistribution.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    UserTrendStatistics: typeof import('./../components/index/UserTrendStatistics.vue')['default']
  }
}
